#!/usr/bin/python3
'''0-making_change'''
def makeChange(coins, total)
    '''This function determines the fewest
    number of coins needed to meet a
    given amount total. Given a pile
    of coins of different values'''

