#!/usr/bin/python3

'''This function determines
if all boxes can be opended'''
def canUnlockAll(boxes):
    '''Determines if all boxes can be opened'''
    listLength = len(boxes)
    for box in boxes:
        boxLength = len(box)
        for count in range (boxLength):
            key = box[count]
            for i in (range(listLength) - 1):
              if key == boxes[i + 1]:
                 n == 1
              else:
                 n == 0
                 return False
            return True
